export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_OFFERS_REQUEST = "PRODUCT_OFFERS_REQUEST";
export const PRODUCT_OFFERS_SUCCESS = "PRODUCT_OFFERS_SUCCESS";
export const PRODUCT_OFFERS_FAIL = "PRODUCT_OFFERS_FAIL";
