export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_SUCCESS";

export const ACTIVE_LOGIN_MODAL = "ACTIVE_LOGIN_MODAL";
